baseURL = "https://mosis.xyz/"
title = "mosis.xyz"
[languages]
    [languages.en]
        languageName = "English"
        weight = 1
    [languages.it]
        languageName = "Italiano"
        weight = 2
