#+TITLE: Daniele Moser
#+DESCRIPTION: Me medesimo meco
#+AUTHOR: Daniele Moser
#+EMAIL: dnlmsr0@gmail.com

* 🙋‍♂️ Who am I
Hi, I'm Daniele, I'm a 22 year old guy based in Trentino, Italy. I work as an electronic
designer and embedded software developer in
[[http://www.leos-instruments.com][LEOS]] where my daily work consists
of production management of the electronics which control lasers for
spectroscopy purposes (you can find more info in section [[work:leos]]).

In my free time, you can find me running in the mountains, growing new
technical skills but most importantly being a volunteer firefighter 🚒.

* 🛠️ Technical knowledge
My technical skills are all centered around electronics and programming.

** 💡 Electronics
I studied electronics and automation in high school, after that I took a
2-year course in automation and mechatronics, where I also found interests in
production management and lean production methods.
Here are some skills I know:
- PCB design, mostly done with KiCad
- PCB production and production management
- SMD and THT soldering
- Embedded boards programming

** 🖥️ Informatics
I have always found the IT world to be fascinating, as a fact I spend lot of my free
time discovering new things on this subject. I am also a fan of open source
software and anything that revolves around it, and I always try to find open
source alternatives to get my job done.
These below are some tools and programs I learned in my lifetime:
- Linux
- Git
- KiCad
- C for embedded systems
- Latex
- Python

* 🎓 Education
** High school degree in Electronics and Automation (2015 - 2018)
I graduated in 2018 in Electronics and Automation, my thesis was about a project
of a Rubik's cube solver, where I covered most of the electronics and programming.

** Alta Formazione Professionale in Mechatronics and Automation (2018 - 2020)
I also took a 2 year course in Mechatronics and Automation. This course
alternates lessons with 8 months of internship (you can find more info in
section [[work:blm]]) so not only studying is involved but I also managed to build
some work experience.

My thesis revolved around the digitization process of the production facility
and lean production methods used in the factory.

* 👨‍💻 Work experience
** LEOS S.r.l. (January 2021 - today) <<work:leos>>
I am currently working in a production environment where I manage the production
and quality assurance of the electronics which control laser heads used for
spectroscopy purposes. 

** BLM group (8 months in 2019 - 2020) <<work:blm>>
I worked as a intern in Adige S.p.a. where I performed various tasks in the
production facility of laser cutting machinery. The tasks include:
- Inventory management
- Production of mechanical pieces with CNC machines
- Followed the full production start to finish (both mechanical and electric) of
  a laser tube-cutting machine
 
Most importantly, I followed the digitization process of the production
facility, which aimed to better estimate the production status of each machine.
Furthermore I took part in the realization of a proof of concept of
digitization of the building procedures.

** ACE control systems LTD (August 2017)
I worked as an intern in Ireland which was part of a school project. I worked in
a workshop mostly doing cabling of electrical cabinets.

** Tretec S.r.l. (June 2017)
I worked as an intern in a PCB production company, where I learned the
basics of THT and SMD soldering. Furthermore this was the first time I managed
to see the production and testing process of PCBs.

* 📧 Contacts
- Email: [[mailto:dnlmsr0@gmail.com][dnlmsr0@gmail.com]]
- LinkedIn: [[https://www.linkedin.com/in/dan-mos][dan-mos]]
- GitHub: [[https://github.com/dnlmsr][dnlmsr]]
