name: github pages

on:
  push:
    branches:
      - develop
    pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - name: Setup Emacs
        uses: leotaku/elisp-check@master
        with:
          file: build-site.el
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          publish_dir: ./docs
