name: github pages

on:
  push:
    branches:
      - master
    pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - name: Setup Emacs
        run: sudo apt-get install -y emacs
      - name: Build
        run: ./build.sh
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: ./public
